### ISSUE TITLE
bleak.exc.BleakError

### ISSUE THREAD

**Issue by Repsycl3d** [cinfulsinamon/BasestationPowerManager#1]
Worked perfectly for a long time but suddenly spits out "Error sending command: <class 'bleak.exc.BleakError'> only.
Tried pressing the buttons, changing ID to other station as mode B, tightening Bluetooth antennas (Connects to my phone perfectly fine from PC) but it's like there's no way to connect over Bluetooth today. Worked fine a few hours ago. No clue.

**Comment by cinfulsinamon** [comment]
Hey, I just updated the script to print the full exception you're getting. Try running it with that to get a better idea of what the issue is. I have had this script go from 100% functional to not working with the same hardware on my end as well though, but it's so inconsistent I was never able to narrow it down.

**Comment by Repsycl3d** [comment]
Still failing but with some sort of explanation. I guess I'll try
reinstalling the Bluetooth driver to see if that fixes it and get back to
you.

Here's the output:

"Current paired base station:
MAC Address: 74:F6:1C:07:16:C5
Unique ID: 4E746C40

Headset VID: 0x045E


Select an option:

1: Choose new base station B
2: Enter Headset Vendor ID
3: Power on base stations (no timeout)
4: Power on base stations (specified timeout)
5: Power off base stations
6: Exit the script
[1-6]: 5

This will send a command to put your base station to sleep.
The base station should power off within a few second after recieving the
command.
Any paired A or C base stations should power off when they are unable to
find a B station.
Continue? (y/n): y
Error sending command: <class 'bleak.exc.BleakError'>: Device with address
74:F6:1C:07:16:C5 was not found. <traceback object at 0x092EC868>
Error sending command: <class 'bleak.exc.BleakError'>: Device with address
74:F6:1C:07:16:C5 was not found. <traceback object at 0x092EC928>
Error sending command: <class 'bleak.exc.BleakError'>: Device with address
74:F6:1C:07:16:C5 was not found. <traceback object at 0x092EC988>
Error sending command: <class 'bleak.exc.BleakError'>: Device with address
74:F6:1C:07:16:C5 was not found. <traceback object at 0x092DEF28>
Error sending command: <class 'bleak.exc.BleakError'>: Device with address
74:F6:1C:07:16:C5 was not found. <traceback object at 0x092DEF68>
Error sending command: <class 'bleak.exc.BleakError'>: Device with address
74:F6:1C:07:16:C5 was not found. <traceback object at 0x092DEEC8>
Error sending command: <class 'bleak.exc.BleakError'>: Device with address
74:F6:1C:07:16:C5 was not found. <traceback object at 0x092DEE88>
Error sending command: <class 'bleak.exc.BleakError'>: Device with address
74:F6:1C:07:16:C5 was not found. <traceback object at 0x092DEAC8>
Error sending command: <class 'bleak.exc.BleakError'>: Device with address
74:F6:1C:07:16:C5 was not found. <traceback object at 0x092DEA88>
Error sending command: <class 'bleak.exc.BleakError'>: Device with address
74:F6:1C:07:16:C5 was not found. <traceback object at 0x092EC988>
Unable to contact base station. Check your bluetooth settings, and ensure
your basestation unique ID is correct.


Press enter to continue..."

**Comment by Repsycl3d** [comment]
I reinstalled seemingly the same driver it already had loaded to my
Bluetooth adapter, and.. it worked! Weird! Thanks for the program. It's
great not having to have my old link box plugged in hogging up a valuable
USB port since I've gone with the Wireless Adapter.
